{{- include "mc-pms.httpConfigMap" (dict
  "component" "admin"
  "prefix" "HTTP_"
  "config" .Values.admin
  "root" .
) }}
{{- include "mc-pms.dbConfig" (dict
  "component" "admin"
  "prefix" "DB_"
  "root" .
) }}
