apiVersion: v2
name: mandacode-service-hub
description: A Helm chart for MandaCode Service Hub - Integrated services (auth and core)
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - oauth
  - authentication
  - microservices
  - multi-tenant

maintainers:
  - name: Mandacode
    email: sauce@mandacode.com