// Code generated by ent, DO NOT EDIT.

package clientapp

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/mandacode-com/serengeti-integrated/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldPublicID, v))
}

// SecretHash applies equality check predicate on the "secret_hash" field. It's identical to SecretHashEQ.
func SecretHash(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldSecretHash, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldDescription, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldUpdatedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v uuid.UUID) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldPublicID, v))
}

// SecretHashEQ applies the EQ predicate on the "secret_hash" field.
func SecretHashEQ(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldSecretHash, v))
}

// SecretHashNEQ applies the NEQ predicate on the "secret_hash" field.
func SecretHashNEQ(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldSecretHash, v))
}

// SecretHashIn applies the In predicate on the "secret_hash" field.
func SecretHashIn(vs ...[]byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldSecretHash, vs...))
}

// SecretHashNotIn applies the NotIn predicate on the "secret_hash" field.
func SecretHashNotIn(vs ...[]byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldSecretHash, vs...))
}

// SecretHashGT applies the GT predicate on the "secret_hash" field.
func SecretHashGT(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldSecretHash, v))
}

// SecretHashGTE applies the GTE predicate on the "secret_hash" field.
func SecretHashGTE(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldSecretHash, v))
}

// SecretHashLT applies the LT predicate on the "secret_hash" field.
func SecretHashLT(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldSecretHash, v))
}

// SecretHashLTE applies the LTE predicate on the "secret_hash" field.
func SecretHashLTE(v []byte) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldSecretHash, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldContainsFold(FieldDescription, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ClientApp {
	return predicate.ClientApp(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasService applies the HasEdge predicate on the "service" edge.
func HasService() predicate.ClientApp {
	return predicate.ClientApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ServiceTable, ServiceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasServiceWith applies the HasEdge predicate on the "service" edge with a given conditions (other predicates).
func HasServiceWith(preds ...predicate.Service) predicate.ClientApp {
	return predicate.ClientApp(func(s *sql.Selector) {
		step := newServiceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWebOauths applies the HasEdge predicate on the "web_oauths" edge.
func HasWebOauths() predicate.ClientApp {
	return predicate.ClientApp(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, WebOauthsTable, WebOauthsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWebOauthsWith applies the HasEdge predicate on the "web_oauths" edge with a given conditions (other predicates).
func HasWebOauthsWith(preds ...predicate.WebOAuth) predicate.ClientApp {
	return predicate.ClientApp(func(s *sql.Selector) {
		step := newWebOauthsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientApp) predicate.ClientApp {
	return predicate.ClientApp(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientApp) predicate.ClientApp {
	return predicate.ClientApp(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientApp) predicate.ClientApp {
	return predicate.ClientApp(sql.NotPredicates(p))
}
