// Package management Code generated by swaggo/swag. DO NOT EDIT
package management

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/client-access/verify": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Verify client application credentials using Basic Authentication (client_id:client_secret)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-access"
                ],
                "summary": "Verify client credentials",
                "responses": {
                    "200": {
                        "description": "Client verification result",
                        "schema": {
                            "$ref": "#/definitions/client_access.VerifyClientResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client-apps": {
            "get": {
                "description": "List all OAuth client applications for a specific service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-apps"
                ],
                "summary": "List client apps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "service_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of client apps",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.ListClientAppsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new OAuth client application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-apps"
                ],
                "summary": "Create a new client app",
                "parameters": [
                    {
                        "description": "Client app creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.CreateClientAppRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created client app with secret",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.CreateClientAppResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client-apps/{id}": {
            "put": {
                "description": "Update an existing OAuth client application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-apps"
                ],
                "summary": "Update a client app",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client App ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Client app update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.UpdateClientAppRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated client app",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.UpdateClientAppResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/client-apps/{id}/refresh-secret": {
            "post": {
                "description": "Generate a new secret for an OAuth client application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client-apps"
                ],
                "summary": "Refresh client app secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client App ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "New secret",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.RefreshSecretResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/services": {
            "post": {
                "description": "Create a new multi-tenant service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Create a new service",
                "parameters": [
                    {
                        "description": "Service creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_service_mgmt.CreateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created service",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_service_mgmt.CreateServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Resource not found",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/services/{id}": {
            "put": {
                "description": "Update an existing multi-tenant service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "services"
                ],
                "summary": "Update a service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service update request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_service_mgmt.UpdateServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated service",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_handler_service_mgmt.UpdateServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Resource not found",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "client_access.ClientAppResponse": {
            "type": "object",
            "properties": {
                "client_app_id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "client_access.ServiceInfoResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                }
            }
        },
        "client_access.VerifyClientResponse": {
            "type": "object",
            "properties": {
                "client_app": {
                    "$ref": "#/definitions/client_access.ClientAppResponse"
                },
                "is_valid": {
                    "type": "boolean"
                },
                "service_id": {
                    "type": "string"
                },
                "service_info": {
                    "$ref": "#/definitions/client_access.ServiceInfoResponse"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.ClientAppResponse": {
            "type": "object",
            "properties": {
                "client_app_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.CreateClientAppRequest": {
            "type": "object",
            "required": [
                "name",
                "service_id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Description of my application"
                },
                "name": {
                    "type": "string",
                    "example": "My App"
                },
                "service_id": {
                    "type": "string",
                    "example": "srv_1234567890abcdef"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.CreateClientAppResponse": {
            "type": "object",
            "properties": {
                "client_app_id": {
                    "type": "string",
                    "example": "app_abcdef1234567890"
                },
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Description of my application"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "My App"
                },
                "secret": {
                    "type": "string",
                    "example": "secret_xyz789abc123def456"
                },
                "service_id": {
                    "type": "string",
                    "example": "srv_1234567890abcdef"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.ListClientAppsResponse": {
            "type": "object",
            "properties": {
                "client_apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_adapter_handler_clientapp_mgmt.ClientAppResponse"
                    }
                },
                "service_id": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.RefreshSecretResponse": {
            "type": "object",
            "properties": {
                "secret": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.UpdateClientAppRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler_clientapp_mgmt.UpdateClientAppResponse": {
            "type": "object",
            "properties": {
                "client_app_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler_service_mgmt.CreateServiceRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Service description"
                },
                "name": {
                    "type": "string",
                    "example": "My Service"
                }
            }
        },
        "internal_adapter_handler_service_mgmt.CreateServiceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Service description"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "My Service"
                },
                "service_id": {
                    "type": "string",
                    "example": "srv_1234567890abcdef"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                }
            }
        },
        "internal_adapter_handler_service_mgmt.UpdateServiceRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_handler_service_mgmt.UpdateServiceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "service_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "merr.ErrCode": {
            "type": "string",
            "enum": [
                "unknown",
                "not_found",
                "invalid_input",
                "permission_denied",
                "internal_server_error",
                "timeout",
                "conflict",
                "unauthorized",
                "bad_request",
                "service_unavailable",
                "too_many_requests",
                "gateway_timeout",
                "unprocessable_entity",
                "not_implemented",
                "method_not_allowed",
                "forbidden",
                "precondition_failed",
                "expectation_failed",
                "bad_gateway",
                "length_required",
                "unsupported_media_type",
                "range_not_satisfiable",
                "insufficient_storage",
                "loop_detected",
                "not_acceptable",
                "too_early",
                "request_header_fields_too_large"
            ],
            "x-enum-varnames": [
                "ErrUnknown",
                "ErrNotFound",
                "ErrInvalidInput",
                "ErrPermissionDenied",
                "ErrInternalServerError",
                "ErrTimeout",
                "ErrConflict",
                "ErrUnauthorized",
                "ErrBadRequest",
                "ErrServiceUnavailable",
                "ErrTooManyRequests",
                "ErrGatewayTimeout",
                "ErrUnprocessableEntity",
                "ErrNotImplemented",
                "ErrMethodNotAllowed",
                "ErrForbidden",
                "ErrPreconditionFailed",
                "ErrExpectationFailed",
                "ErrBadGateway",
                "ErrLengthRequired",
                "ErrUnsupportedMediaType",
                "ErrRangeNotSatisfiable",
                "ErrInsufficientStorage",
                "ErrLoopDetected",
                "ErrNotAcceptable",
                "ErrTooEarly",
                "ErrRequestHeaderFieldsTooLarge"
            ]
        },
        "merrmid.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/merr.ErrCode"
                },
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "MandaCode Service Hub Management API",
	Description:      "Multi-tenant service and client application management API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
