// Code generated by MockGen. DO NOT EDIT.
// Source: internal/port/out/repo_clientapp.go
//
// Generated by this command:
//
//	mockgen -source=internal/port/out/repo_clientapp.go -destination=internal/test/mock/repo_clientapp_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/mandacode-com/mandacode-ssam/internal/domain/entity"
	value_object "github.com/mandacode-com/mandacode-ssam/internal/domain/vo"
	out "github.com/mandacode-com/mandacode-ssam/internal/port/out"
	gomock "go.uber.org/mock/gomock"
)

// MockClientAppRepository is a mock of ClientAppRepository interface.
type MockClientAppRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientAppRepositoryMockRecorder
	isgomock struct{}
}

// MockClientAppRepositoryMockRecorder is the mock recorder for MockClientAppRepository.
type MockClientAppRepositoryMockRecorder struct {
	mock *MockClientAppRepository
}

// NewMockClientAppRepository creates a new mock instance.
func NewMockClientAppRepository(ctrl *gomock.Controller) *MockClientAppRepository {
	mock := &MockClientAppRepository{ctrl: ctrl}
	mock.recorder = &MockClientAppRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAppRepository) EXPECT() *MockClientAppRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClientAppRepository) Create(ctx context.Context, tx out.Tx, clientApp *entity.ClientApp) (*entity.ClientApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, clientApp)
	ret0, _ := ret[0].(*entity.ClientApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClientAppRepositoryMockRecorder) Create(ctx, tx, clientApp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClientAppRepository)(nil).Create), ctx, tx, clientApp)
}

// Delete mocks base method.
func (m *MockClientAppRepository) Delete(ctx context.Context, tx out.Tx, clientApp *entity.ClientApp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, clientApp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientAppRepositoryMockRecorder) Delete(ctx, tx, clientApp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientAppRepository)(nil).Delete), ctx, tx, clientApp)
}

// FindByID mocks base method.
func (m *MockClientAppRepository) FindByID(ctx context.Context, id value_object.ClientAppID) (*entity.ClientApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.ClientApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClientAppRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClientAppRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockClientAppRepository) Update(ctx context.Context, tx out.Tx, clientApp *entity.ClientApp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, clientApp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClientAppRepositoryMockRecorder) Update(ctx, tx, clientApp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClientAppRepository)(nil).Update), ctx, tx, clientApp)
}

// MockClientAppQueryRepository is a mock of ClientAppQueryRepository interface.
type MockClientAppQueryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClientAppQueryRepositoryMockRecorder
	isgomock struct{}
}

// MockClientAppQueryRepositoryMockRecorder is the mock recorder for MockClientAppQueryRepository.
type MockClientAppQueryRepositoryMockRecorder struct {
	mock *MockClientAppQueryRepository
}

// NewMockClientAppQueryRepository creates a new mock instance.
func NewMockClientAppQueryRepository(ctrl *gomock.Controller) *MockClientAppQueryRepository {
	mock := &MockClientAppQueryRepository{ctrl: ctrl}
	mock.recorder = &MockClientAppQueryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAppQueryRepository) EXPECT() *MockClientAppQueryRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockClientAppQueryRepository) FindByID(ctx context.Context, id value_object.ClientAppID) (*entity.ClientApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.ClientApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockClientAppQueryRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockClientAppQueryRepository)(nil).FindByID), ctx, id)
}

// FindByName mocks base method.
func (m *MockClientAppQueryRepository) FindByName(ctx context.Context, name string) (*entity.ClientApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*entity.ClientApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockClientAppQueryRepositoryMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockClientAppQueryRepository)(nil).FindByName), ctx, name)
}

// FindByPublicID mocks base method.
func (m *MockClientAppQueryRepository) FindByPublicID(ctx context.Context, publicID value_object.ClientAppPublicID) (*entity.ClientApp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPublicID", ctx, publicID)
	ret0, _ := ret[0].(*entity.ClientApp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPublicID indicates an expected call of FindByPublicID.
func (mr *MockClientAppQueryRepositoryMockRecorder) FindByPublicID(ctx, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPublicID", reflect.TypeOf((*MockClientAppQueryRepository)(nil).FindByPublicID), ctx, publicID)
}

// List mocks base method.
func (m *MockClientAppQueryRepository) List(ctx context.Context, filter *out.ClientAppListFilter, options *out.ClientAppListOptions) ([]*entity.ClientApp, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, options)
	ret0, _ := ret[0].([]*entity.ClientApp)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockClientAppQueryRepositoryMockRecorder) List(ctx, filter, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClientAppQueryRepository)(nil).List), ctx, filter, options)
}
