{{- if .Values.client.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defined.client.configMapName" . }}
  labels:
    {{- include "defined.client.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.client.env | default "prod" | quote }}
  PORT: "8080"
  READ_TIMEOUT: {{ .Values.client.server.readTimeout | quote }}
  WRITE_TIMEOUT: {{ .Values.client.server.writeTimeout | quote }}
  READ_HEADER_TIMEOUT: {{ .Values.client.server.readHeaderTimeout | quote }}
  IDLE_TIMEOUT: {{ .Values.client.server.idleTimeout | quote }}
{{- end }}
