// Package client Code generated by swaggo/swag. DO NOT EDIT
package client

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://mandacode.com/terms",
        "contact": {
            "name": "API Support",
            "url": "https://mandacode.com/support",
            "email": "support@mandacode.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/namespaces/{id}": {
            "get": {
                "description": "Get a namespace by its ID (read-only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Get namespace by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Namespace ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Namespace found",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http_handler_client_ns.GetByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Namespace not found",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/validate": {
            "get": {
                "description": "Check if a project belongs to a specific namespace",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Validate project-namespace relationship",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Namespace ID",
                        "name": "namespace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Validation result",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http_handler_client_project.IsValidProjectNamespaceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{id}": {
            "get": {
                "description": "Get a project by its ID (read-only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "client"
                ],
                "summary": "Get project by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Project found",
                        "schema": {
                            "$ref": "#/definitions/internal_adapter_http_handler_client_project.GetByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Project not found",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/merrmid.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_adapter_http_handler_client_ns.GetByIDResponse": {
            "type": "object",
            "properties": {
                "namespace": {
                    "$ref": "#/definitions/internal_adapter_http_handler_client_ns.NamespaceResponse"
                }
            }
        },
        "internal_adapter_http_handler_client_ns.NamespaceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_adapter_http_handler_client_project.GetByIDResponse": {
            "type": "object",
            "properties": {
                "project": {
                    "$ref": "#/definitions/internal_adapter_http_handler_client_project.ProjectResponse"
                }
            }
        },
        "internal_adapter_http_handler_client_project.IsValidProjectNamespaceResponse": {
            "type": "object",
            "properties": {
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "internal_adapter_http_handler_client_project.ProjectResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace_id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "merr.ErrCode": {
            "type": "string",
            "enum": [
                "unknown",
                "not_found",
                "invalid_input",
                "permission_denied",
                "internal_server_error",
                "timeout",
                "conflict",
                "unauthorized",
                "bad_request",
                "service_unavailable",
                "too_many_requests",
                "gateway_timeout",
                "unprocessable_entity",
                "not_implemented",
                "method_not_allowed",
                "forbidden",
                "precondition_failed",
                "expectation_failed",
                "bad_gateway",
                "length_required",
                "unsupported_media_type",
                "range_not_satisfiable",
                "insufficient_storage",
                "loop_detected",
                "not_acceptable",
                "too_early",
                "request_header_fields_too_large"
            ],
            "x-enum-varnames": [
                "ErrUnknown",
                "ErrNotFound",
                "ErrInvalidInput",
                "ErrPermissionDenied",
                "ErrInternalServerError",
                "ErrTimeout",
                "ErrConflict",
                "ErrUnauthorized",
                "ErrBadRequest",
                "ErrServiceUnavailable",
                "ErrTooManyRequests",
                "ErrGatewayTimeout",
                "ErrUnprocessableEntity",
                "ErrNotImplemented",
                "ErrMethodNotAllowed",
                "ErrForbidden",
                "ErrPreconditionFailed",
                "ErrExpectationFailed",
                "ErrBadGateway",
                "ErrLengthRequired",
                "ErrUnsupportedMediaType",
                "ErrRangeNotSatisfiable",
                "ErrInsufficientStorage",
                "ErrLoopDetected",
                "ErrNotAcceptable",
                "ErrTooEarly",
                "ErrRequestHeaderFieldsTooLarge"
            ]
        },
        "merrmid.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/merr.ErrCode"
                },
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Client read-only operations for namespace and project access",
            "name": "client"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "pms.mandacode.com",
	BasePath:         "/api/client/v1",
	Schemes:          []string{"http", "https"},
	Title:            "MandaCode PMS Client API",
	Description:      "Client API for MandaCode Project Management System - read-only access to namespaces and projects",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
