// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-com/mandacode-service-hub/ent/clientapp"
	"github.com/mandacode-com/mandacode-service-hub/ent/service"
	"github.com/mandacode-com/mandacode-service-hub/ent/weboauth"
)

// ClientAppCreate is the builder for creating a ClientApp entity.
type ClientAppCreate struct {
	config
	mutation *ClientAppMutation
	hooks    []Hook
}

// SetServiceID sets the "service_id" field.
func (_c *ClientAppCreate) SetServiceID(v int64) *ClientAppCreate {
	_c.mutation.SetServiceID(v)
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *ClientAppCreate) SetPublicID(v uuid.UUID) *ClientAppCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_c *ClientAppCreate) SetNillablePublicID(v *uuid.UUID) *ClientAppCreate {
	if v != nil {
		_c.SetPublicID(*v)
	}
	return _c
}

// SetSecretHash sets the "secret_hash" field.
func (_c *ClientAppCreate) SetSecretHash(v []byte) *ClientAppCreate {
	_c.mutation.SetSecretHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ClientAppCreate) SetName(v string) *ClientAppCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ClientAppCreate) SetDescription(v string) *ClientAppCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ClientAppCreate) SetNillableDescription(v *string) *ClientAppCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ClientAppCreate) SetIsActive(v bool) *ClientAppCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ClientAppCreate) SetNillableIsActive(v *bool) *ClientAppCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ClientAppCreate) SetCreatedAt(v time.Time) *ClientAppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ClientAppCreate) SetNillableCreatedAt(v *time.Time) *ClientAppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ClientAppCreate) SetUpdatedAt(v time.Time) *ClientAppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ClientAppCreate) SetNillableUpdatedAt(v *time.Time) *ClientAppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ClientAppCreate) SetID(v int64) *ClientAppCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetService sets the "service" edge to the Service entity.
func (_c *ClientAppCreate) SetService(v *Service) *ClientAppCreate {
	return _c.SetServiceID(v.ID)
}

// AddWebOauthIDs adds the "web_oauths" edge to the WebOAuth entity by IDs.
func (_c *ClientAppCreate) AddWebOauthIDs(ids ...int64) *ClientAppCreate {
	_c.mutation.AddWebOauthIDs(ids...)
	return _c
}

// AddWebOauths adds the "web_oauths" edges to the WebOAuth entity.
func (_c *ClientAppCreate) AddWebOauths(v ...*WebOAuth) *ClientAppCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWebOauthIDs(ids...)
}

// Mutation returns the ClientAppMutation object of the builder.
func (_c *ClientAppCreate) Mutation() *ClientAppMutation {
	return _c.mutation
}

// Save creates the ClientApp in the database.
func (_c *ClientAppCreate) Save(ctx context.Context) (*ClientApp, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClientAppCreate) SaveX(ctx context.Context) *ClientApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientAppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientAppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClientAppCreate) defaults() {
	if _, ok := _c.mutation.PublicID(); !ok {
		v := clientapp.DefaultPublicID()
		_c.mutation.SetPublicID(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := clientapp.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := clientapp.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := clientapp.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClientAppCreate) check() error {
	if _, ok := _c.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service_id", err: errors.New(`ent: missing required field "ClientApp.service_id"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "ClientApp.public_id"`)}
	}
	if _, ok := _c.mutation.SecretHash(); !ok {
		return &ValidationError{Name: "secret_hash", err: errors.New(`ent: missing required field "ClientApp.secret_hash"`)}
	}
	if v, ok := _c.mutation.SecretHash(); ok {
		if err := clientapp.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "ClientApp.secret_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ClientApp.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := clientapp.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ClientApp.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ClientApp.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ClientApp.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ClientApp.updated_at"`)}
	}
	if len(_c.mutation.ServiceIDs()) == 0 {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required edge "ClientApp.service"`)}
	}
	return nil
}

func (_c *ClientAppCreate) sqlSave(ctx context.Context) (*ClientApp, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClientAppCreate) createSpec() (*ClientApp, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientApp{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clientapp.Table, sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(clientapp.FieldPublicID, field.TypeUUID, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.SecretHash(); ok {
		_spec.SetField(clientapp.FieldSecretHash, field.TypeBytes, value)
		_node.SecretHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(clientapp.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(clientapp.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(clientapp.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(clientapp.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(clientapp.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clientapp.ServiceTable,
			Columns: []string{clientapp.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WebOauthsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clientapp.WebOauthsTable,
			Columns: []string{clientapp.WebOauthsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weboauth.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClientAppCreateBulk is the builder for creating many ClientApp entities in bulk.
type ClientAppCreateBulk struct {
	config
	err      error
	builders []*ClientAppCreate
}

// Save creates the ClientApp entities in the database.
func (_c *ClientAppCreateBulk) Save(ctx context.Context) ([]*ClientApp, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClientApp, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientAppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClientAppCreateBulk) SaveX(ctx context.Context) []*ClientApp {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClientAppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClientAppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
