// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/mandacode-com/mandacode-ssam/ent/clientapp"
	"github.com/mandacode-com/mandacode-ssam/ent/service"
)

// ClientApp is the model entity for the ClientApp schema.
type ClientApp struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ServiceID holds the value of the "service_id" field.
	ServiceID int64 `json:"service_id,omitempty"`
	// PublicID holds the value of the "public_id" field.
	PublicID uuid.UUID `json:"public_id,omitempty"`
	// SecretHash holds the value of the "secret_hash" field.
	SecretHash []byte `json:"secret_hash,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ClientAppQuery when eager-loading is set.
	Edges        ClientAppEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ClientAppEdges holds the relations/edges for other nodes in the graph.
type ClientAppEdges struct {
	// Service holds the value of the service edge.
	Service *Service `json:"service,omitempty"`
	// WebOauths holds the value of the web_oauths edge.
	WebOauths []*WebOAuth `json:"web_oauths,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ServiceOrErr returns the Service value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ClientAppEdges) ServiceOrErr() (*Service, error) {
	if e.Service != nil {
		return e.Service, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: service.Label}
	}
	return nil, &NotLoadedError{edge: "service"}
}

// WebOauthsOrErr returns the WebOauths value or an error if the edge
// was not loaded in eager-loading.
func (e ClientAppEdges) WebOauthsOrErr() ([]*WebOAuth, error) {
	if e.loadedTypes[1] {
		return e.WebOauths, nil
	}
	return nil, &NotLoadedError{edge: "web_oauths"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ClientApp) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case clientapp.FieldSecretHash:
			values[i] = new([]byte)
		case clientapp.FieldIsActive:
			values[i] = new(sql.NullBool)
		case clientapp.FieldID, clientapp.FieldServiceID:
			values[i] = new(sql.NullInt64)
		case clientapp.FieldName, clientapp.FieldDescription:
			values[i] = new(sql.NullString)
		case clientapp.FieldCreatedAt, clientapp.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case clientapp.FieldPublicID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ClientApp fields.
func (_m *ClientApp) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case clientapp.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case clientapp.FieldServiceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field service_id", values[i])
			} else if value.Valid {
				_m.ServiceID = value.Int64
			}
		case clientapp.FieldPublicID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field public_id", values[i])
			} else if value != nil {
				_m.PublicID = *value
			}
		case clientapp.FieldSecretHash:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field secret_hash", values[i])
			} else if value != nil {
				_m.SecretHash = *value
			}
		case clientapp.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case clientapp.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case clientapp.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case clientapp.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case clientapp.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ClientApp.
// This includes values selected through modifiers, order, etc.
func (_m *ClientApp) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryService queries the "service" edge of the ClientApp entity.
func (_m *ClientApp) QueryService() *ServiceQuery {
	return NewClientAppClient(_m.config).QueryService(_m)
}

// QueryWebOauths queries the "web_oauths" edge of the ClientApp entity.
func (_m *ClientApp) QueryWebOauths() *WebOAuthQuery {
	return NewClientAppClient(_m.config).QueryWebOauths(_m)
}

// Update returns a builder for updating this ClientApp.
// Note that you need to call ClientApp.Unwrap() before calling this method if this ClientApp
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ClientApp) Update() *ClientAppUpdateOne {
	return NewClientAppClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ClientApp entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ClientApp) Unwrap() *ClientApp {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ClientApp is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ClientApp) String() string {
	var builder strings.Builder
	builder.WriteString("ClientApp(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("service_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ServiceID))
	builder.WriteString(", ")
	builder.WriteString("public_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublicID))
	builder.WriteString(", ")
	builder.WriteString("secret_hash=")
	builder.WriteString(fmt.Sprintf("%v", _m.SecretHash))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ClientApps is a parsable slice of ClientApp.
type ClientApps []*ClientApp
