// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-com/serengeti-integrated/ent/service"
	"github.com/mandacode-com/serengeti-integrated/ent/serviceclient"
	"github.com/mandacode-com/serengeti-integrated/ent/weboauth"
)

// ServiceClientCreate is the builder for creating a ServiceClient entity.
type ServiceClientCreate struct {
	config
	mutation *ServiceClientMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *ServiceClientCreate) SetPublicID(v uuid.UUID) *ServiceClientCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_c *ServiceClientCreate) SetNillablePublicID(v *uuid.UUID) *ServiceClientCreate {
	if v != nil {
		_c.SetPublicID(*v)
	}
	return _c
}

// SetSecretHash sets the "secret_hash" field.
func (_c *ServiceClientCreate) SetSecretHash(v []byte) *ServiceClientCreate {
	_c.mutation.SetSecretHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ServiceClientCreate) SetName(v string) *ServiceClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ServiceClientCreate) SetDescription(v string) *ServiceClientCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ServiceClientCreate) SetNillableDescription(v *string) *ServiceClientCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *ServiceClientCreate) SetIsActive(v bool) *ServiceClientCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *ServiceClientCreate) SetNillableIsActive(v *bool) *ServiceClientCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ServiceClientCreate) SetCreatedAt(v time.Time) *ServiceClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ServiceClientCreate) SetNillableCreatedAt(v *time.Time) *ServiceClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ServiceClientCreate) SetUpdatedAt(v time.Time) *ServiceClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ServiceClientCreate) SetNillableUpdatedAt(v *time.Time) *ServiceClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ServiceClientCreate) SetID(v int64) *ServiceClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetServiceID sets the "service" edge to the Service entity by ID.
func (_c *ServiceClientCreate) SetServiceID(id int64) *ServiceClientCreate {
	_c.mutation.SetServiceID(id)
	return _c
}

// SetService sets the "service" edge to the Service entity.
func (_c *ServiceClientCreate) SetService(v *Service) *ServiceClientCreate {
	return _c.SetServiceID(v.ID)
}

// AddWebOauthIDs adds the "web_oauth" edge to the WebOAuth entity by IDs.
func (_c *ServiceClientCreate) AddWebOauthIDs(ids ...int64) *ServiceClientCreate {
	_c.mutation.AddWebOauthIDs(ids...)
	return _c
}

// AddWebOauth adds the "web_oauth" edges to the WebOAuth entity.
func (_c *ServiceClientCreate) AddWebOauth(v ...*WebOAuth) *ServiceClientCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddWebOauthIDs(ids...)
}

// Mutation returns the ServiceClientMutation object of the builder.
func (_c *ServiceClientCreate) Mutation() *ServiceClientMutation {
	return _c.mutation
}

// Save creates the ServiceClient in the database.
func (_c *ServiceClientCreate) Save(ctx context.Context) (*ServiceClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ServiceClientCreate) SaveX(ctx context.Context) *ServiceClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ServiceClientCreate) defaults() {
	if _, ok := _c.mutation.PublicID(); !ok {
		v := serviceclient.DefaultPublicID()
		_c.mutation.SetPublicID(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := serviceclient.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := serviceclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := serviceclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ServiceClientCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "ServiceClient.public_id"`)}
	}
	if _, ok := _c.mutation.SecretHash(); !ok {
		return &ValidationError{Name: "secret_hash", err: errors.New(`ent: missing required field "ServiceClient.secret_hash"`)}
	}
	if v, ok := _c.mutation.SecretHash(); ok {
		if err := serviceclient.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "ServiceClient.secret_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ServiceClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := serviceclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ServiceClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "ServiceClient.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ServiceClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ServiceClient.updated_at"`)}
	}
	if len(_c.mutation.ServiceIDs()) == 0 {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required edge "ServiceClient.service"`)}
	}
	return nil
}

func (_c *ServiceClientCreate) sqlSave(ctx context.Context) (*ServiceClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ServiceClientCreate) createSpec() (*ServiceClient, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(serviceclient.Table, sqlgraph.NewFieldSpec(serviceclient.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(serviceclient.FieldPublicID, field.TypeUUID, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.SecretHash(); ok {
		_spec.SetField(serviceclient.FieldSecretHash, field.TypeBytes, value)
		_node.SecretHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(serviceclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(serviceclient.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(serviceclient.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(serviceclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(serviceclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   serviceclient.ServiceTable,
			Columns: []string{serviceclient.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.service_clients = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.WebOauthIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   serviceclient.WebOauthTable,
			Columns: []string{serviceclient.WebOauthColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(weboauth.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ServiceClientCreateBulk is the builder for creating many ServiceClient entities in bulk.
type ServiceClientCreateBulk struct {
	config
	err      error
	builders []*ServiceClientCreate
}

// Save creates the ServiceClient entities in the database.
func (_c *ServiceClientCreateBulk) Save(ctx context.Context) ([]*ServiceClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ServiceClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ServiceClientCreateBulk) SaveX(ctx context.Context) []*ServiceClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ServiceClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ServiceClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
