// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-com/mandacode-service-hub/ent/clientapp"
	"github.com/mandacode-com/mandacode-service-hub/ent/predicate"
	"github.com/mandacode-com/mandacode-service-hub/ent/service"
	"github.com/mandacode-com/mandacode-service-hub/ent/useridentity"
)

// ServiceUpdate is the builder for updating Service entities.
type ServiceUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceMutation
}

// Where appends a list predicates to the ServiceUpdate builder.
func (_u *ServiceUpdate) Where(ps ...predicate.Service) *ServiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *ServiceUpdate) SetPublicID(v uuid.UUID) *ServiceUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillablePublicID(v *uuid.UUID) *ServiceUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ServiceUpdate) SetName(v string) *ServiceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableName(v *string) *ServiceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceUpdate) SetDescription(v string) *ServiceUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableDescription(v *string) *ServiceUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceUpdate) ClearDescription() *ServiceUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ServiceUpdate) SetIsActive(v bool) *ServiceUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ServiceUpdate) SetNillableIsActive(v *bool) *ServiceUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceUpdate) SetUpdatedAt(v time.Time) *ServiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddClientAppIDs adds the "client_apps" edge to the ClientApp entity by IDs.
func (_u *ServiceUpdate) AddClientAppIDs(ids ...int64) *ServiceUpdate {
	_u.mutation.AddClientAppIDs(ids...)
	return _u
}

// AddClientApps adds the "client_apps" edges to the ClientApp entity.
func (_u *ServiceUpdate) AddClientApps(v ...*ClientApp) *ServiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientAppIDs(ids...)
}

// AddUserIdentityIDs adds the "user_identities" edge to the UserIdentity entity by IDs.
func (_u *ServiceUpdate) AddUserIdentityIDs(ids ...int64) *ServiceUpdate {
	_u.mutation.AddUserIdentityIDs(ids...)
	return _u
}

// AddUserIdentities adds the "user_identities" edges to the UserIdentity entity.
func (_u *ServiceUpdate) AddUserIdentities(v ...*UserIdentity) *ServiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIdentityIDs(ids...)
}

// Mutation returns the ServiceMutation object of the builder.
func (_u *ServiceUpdate) Mutation() *ServiceMutation {
	return _u.mutation
}

// ClearClientApps clears all "client_apps" edges to the ClientApp entity.
func (_u *ServiceUpdate) ClearClientApps() *ServiceUpdate {
	_u.mutation.ClearClientApps()
	return _u
}

// RemoveClientAppIDs removes the "client_apps" edge to ClientApp entities by IDs.
func (_u *ServiceUpdate) RemoveClientAppIDs(ids ...int64) *ServiceUpdate {
	_u.mutation.RemoveClientAppIDs(ids...)
	return _u
}

// RemoveClientApps removes "client_apps" edges to ClientApp entities.
func (_u *ServiceUpdate) RemoveClientApps(v ...*ClientApp) *ServiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientAppIDs(ids...)
}

// ClearUserIdentities clears all "user_identities" edges to the UserIdentity entity.
func (_u *ServiceUpdate) ClearUserIdentities() *ServiceUpdate {
	_u.mutation.ClearUserIdentities()
	return _u
}

// RemoveUserIdentityIDs removes the "user_identities" edge to UserIdentity entities by IDs.
func (_u *ServiceUpdate) RemoveUserIdentityIDs(ids ...int64) *ServiceUpdate {
	_u.mutation.RemoveUserIdentityIDs(ids...)
	return _u
}

// RemoveUserIdentities removes "user_identities" edges to UserIdentity entities.
func (_u *ServiceUpdate) RemoveUserIdentities(v ...*UserIdentity) *ServiceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIdentityIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := service.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := service.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Service.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(service.FieldPublicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(service.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(service.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(service.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(service.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClientAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.ClientAppsTable,
			Columns: []string{service.ClientAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientAppsIDs(); len(nodes) > 0 && !_u.mutation.ClientAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.ClientAppsTable,
			Columns: []string{service.ClientAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientAppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.ClientAppsTable,
			Columns: []string{service.ClientAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.UserIdentitiesTable,
			Columns: []string{service.UserIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.UserIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.UserIdentitiesTable,
			Columns: []string{service.UserIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.UserIdentitiesTable,
			Columns: []string{service.UserIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceUpdateOne is the builder for updating a single Service entity.
type ServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceMutation
}

// SetPublicID sets the "public_id" field.
func (_u *ServiceUpdateOne) SetPublicID(v uuid.UUID) *ServiceUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillablePublicID(v *uuid.UUID) *ServiceUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ServiceUpdateOne) SetName(v string) *ServiceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableName(v *string) *ServiceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ServiceUpdateOne) SetDescription(v string) *ServiceUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableDescription(v *string) *ServiceUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ServiceUpdateOne) ClearDescription() *ServiceUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *ServiceUpdateOne) SetIsActive(v bool) *ServiceUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *ServiceUpdateOne) SetNillableIsActive(v *bool) *ServiceUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceUpdateOne) SetUpdatedAt(v time.Time) *ServiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddClientAppIDs adds the "client_apps" edge to the ClientApp entity by IDs.
func (_u *ServiceUpdateOne) AddClientAppIDs(ids ...int64) *ServiceUpdateOne {
	_u.mutation.AddClientAppIDs(ids...)
	return _u
}

// AddClientApps adds the "client_apps" edges to the ClientApp entity.
func (_u *ServiceUpdateOne) AddClientApps(v ...*ClientApp) *ServiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddClientAppIDs(ids...)
}

// AddUserIdentityIDs adds the "user_identities" edge to the UserIdentity entity by IDs.
func (_u *ServiceUpdateOne) AddUserIdentityIDs(ids ...int64) *ServiceUpdateOne {
	_u.mutation.AddUserIdentityIDs(ids...)
	return _u
}

// AddUserIdentities adds the "user_identities" edges to the UserIdentity entity.
func (_u *ServiceUpdateOne) AddUserIdentities(v ...*UserIdentity) *ServiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIdentityIDs(ids...)
}

// Mutation returns the ServiceMutation object of the builder.
func (_u *ServiceUpdateOne) Mutation() *ServiceMutation {
	return _u.mutation
}

// ClearClientApps clears all "client_apps" edges to the ClientApp entity.
func (_u *ServiceUpdateOne) ClearClientApps() *ServiceUpdateOne {
	_u.mutation.ClearClientApps()
	return _u
}

// RemoveClientAppIDs removes the "client_apps" edge to ClientApp entities by IDs.
func (_u *ServiceUpdateOne) RemoveClientAppIDs(ids ...int64) *ServiceUpdateOne {
	_u.mutation.RemoveClientAppIDs(ids...)
	return _u
}

// RemoveClientApps removes "client_apps" edges to ClientApp entities.
func (_u *ServiceUpdateOne) RemoveClientApps(v ...*ClientApp) *ServiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveClientAppIDs(ids...)
}

// ClearUserIdentities clears all "user_identities" edges to the UserIdentity entity.
func (_u *ServiceUpdateOne) ClearUserIdentities() *ServiceUpdateOne {
	_u.mutation.ClearUserIdentities()
	return _u
}

// RemoveUserIdentityIDs removes the "user_identities" edge to UserIdentity entities by IDs.
func (_u *ServiceUpdateOne) RemoveUserIdentityIDs(ids ...int64) *ServiceUpdateOne {
	_u.mutation.RemoveUserIdentityIDs(ids...)
	return _u
}

// RemoveUserIdentities removes "user_identities" edges to UserIdentity entities.
func (_u *ServiceUpdateOne) RemoveUserIdentities(v ...*UserIdentity) *ServiceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIdentityIDs(ids...)
}

// Where appends a list predicates to the ServiceUpdate builder.
func (_u *ServiceUpdateOne) Where(ps ...predicate.Service) *ServiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceUpdateOne) Select(field string, fields ...string) *ServiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Service entity.
func (_u *ServiceUpdateOne) Save(ctx context.Context) (*Service, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceUpdateOne) SaveX(ctx context.Context) *Service {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ServiceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := service.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ServiceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := service.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Service.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ServiceUpdateOne) sqlSave(ctx context.Context) (_node *Service, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Service.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, service.FieldID)
		for _, f := range fields {
			if !service.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != service.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(service.FieldPublicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(service.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(service.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(service.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(service.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClientAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.ClientAppsTable,
			Columns: []string{service.ClientAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedClientAppsIDs(); len(nodes) > 0 && !_u.mutation.ClientAppsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.ClientAppsTable,
			Columns: []string{service.ClientAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientAppsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.ClientAppsTable,
			Columns: []string{service.ClientAppsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.UserIdentitiesTable,
			Columns: []string{service.UserIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIdentitiesIDs(); len(nodes) > 0 && !_u.mutation.UserIdentitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.UserIdentitiesTable,
			Columns: []string{service.UserIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIdentitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   service.UserIdentitiesTable,
			Columns: []string{service.UserIdentitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Service{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
