// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-com/mandacode-ssam/ent/predicate"
	"github.com/mandacode-com/mandacode-ssam/ent/serviceclient"
)

// ServiceClientDelete is the builder for deleting a ServiceClient entity.
type ServiceClientDelete struct {
	config
	hooks    []Hook
	mutation *ServiceClientMutation
}

// Where appends a list predicates to the ServiceClientDelete builder.
func (_d *ServiceClientDelete) Where(ps ...predicate.ServiceClient) *ServiceClientDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ServiceClientDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ServiceClientDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ServiceClientDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(serviceclient.Table, sqlgraph.NewFieldSpec(serviceclient.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ServiceClientDeleteOne is the builder for deleting a single ServiceClient entity.
type ServiceClientDeleteOne struct {
	_d *ServiceClientDelete
}

// Where appends a list predicates to the ServiceClientDelete builder.
func (_d *ServiceClientDeleteOne) Where(ps ...predicate.ServiceClient) *ServiceClientDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ServiceClientDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{serviceclient.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ServiceClientDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
