// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-com/mandacode-ssam/ent/service"
	"github.com/mandacode-com/mandacode-ssam/ent/svcclient"
)

// SvcClientCreate is the builder for creating a SvcClient entity.
type SvcClientCreate struct {
	config
	mutation *SvcClientMutation
	hooks    []Hook
}

// SetServiceID sets the "service_id" field.
func (_c *SvcClientCreate) SetServiceID(v int64) *SvcClientCreate {
	_c.mutation.SetServiceID(v)
	return _c
}

// SetPublicID sets the "public_id" field.
func (_c *SvcClientCreate) SetPublicID(v string) *SvcClientCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetSecretHash sets the "secret_hash" field.
func (_c *SvcClientCreate) SetSecretHash(v []byte) *SvcClientCreate {
	_c.mutation.SetSecretHash(v)
	return _c
}

// SetName sets the "name" field.
func (_c *SvcClientCreate) SetName(v string) *SvcClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *SvcClientCreate) SetDescription(v string) *SvcClientCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SvcClientCreate) SetNillableDescription(v *string) *SvcClientCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *SvcClientCreate) SetIsActive(v bool) *SvcClientCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *SvcClientCreate) SetNillableIsActive(v *bool) *SvcClientCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SvcClientCreate) SetCreatedAt(v time.Time) *SvcClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SvcClientCreate) SetNillableCreatedAt(v *time.Time) *SvcClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SvcClientCreate) SetUpdatedAt(v time.Time) *SvcClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SvcClientCreate) SetNillableUpdatedAt(v *time.Time) *SvcClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SvcClientCreate) SetID(v int64) *SvcClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetService sets the "service" edge to the Service entity.
func (_c *SvcClientCreate) SetService(v *Service) *SvcClientCreate {
	return _c.SetServiceID(v.ID)
}

// Mutation returns the SvcClientMutation object of the builder.
func (_c *SvcClientCreate) Mutation() *SvcClientMutation {
	return _c.mutation
}

// Save creates the SvcClient in the database.
func (_c *SvcClientCreate) Save(ctx context.Context) (*SvcClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SvcClientCreate) SaveX(ctx context.Context) *SvcClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SvcClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SvcClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SvcClientCreate) defaults() {
	if _, ok := _c.mutation.IsActive(); !ok {
		v := svcclient.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := svcclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := svcclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SvcClientCreate) check() error {
	if _, ok := _c.mutation.ServiceID(); !ok {
		return &ValidationError{Name: "service_id", err: errors.New(`ent: missing required field "SvcClient.service_id"`)}
	}
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "SvcClient.public_id"`)}
	}
	if _, ok := _c.mutation.SecretHash(); !ok {
		return &ValidationError{Name: "secret_hash", err: errors.New(`ent: missing required field "SvcClient.secret_hash"`)}
	}
	if v, ok := _c.mutation.SecretHash(); ok {
		if err := svcclient.SecretHashValidator(v); err != nil {
			return &ValidationError{Name: "secret_hash", err: fmt.Errorf(`ent: validator failed for field "SvcClient.secret_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SvcClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := svcclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SvcClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "SvcClient.is_active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SvcClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SvcClient.updated_at"`)}
	}
	if len(_c.mutation.ServiceIDs()) == 0 {
		return &ValidationError{Name: "service", err: errors.New(`ent: missing required edge "SvcClient.service"`)}
	}
	return nil
}

func (_c *SvcClientCreate) sqlSave(ctx context.Context) (*SvcClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SvcClientCreate) createSpec() (*SvcClient, *sqlgraph.CreateSpec) {
	var (
		_node = &SvcClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(svcclient.Table, sqlgraph.NewFieldSpec(svcclient.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(svcclient.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.SecretHash(); ok {
		_spec.SetField(svcclient.FieldSecretHash, field.TypeBytes, value)
		_node.SecretHash = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(svcclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(svcclient.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(svcclient.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(svcclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(svcclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   svcclient.ServiceTable,
			Columns: []string{svcclient.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ServiceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SvcClientCreateBulk is the builder for creating many SvcClient entities in bulk.
type SvcClientCreateBulk struct {
	config
	err      error
	builders []*SvcClientCreate
}

// Save creates the SvcClient entities in the database.
func (_c *SvcClientCreateBulk) Save(ctx context.Context) ([]*SvcClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SvcClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SvcClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SvcClientCreateBulk) SaveX(ctx context.Context) []*SvcClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SvcClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SvcClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
