// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-com/serengeti-integrated/ent/predicate"
	"github.com/mandacode-com/serengeti-integrated/ent/useridentity"
	"github.com/mandacode-com/serengeti-integrated/ent/userinfo"
)

// UserInfoUpdate is the builder for updating UserInfo entities.
type UserInfoUpdate struct {
	config
	hooks    []Hook
	mutation *UserInfoMutation
}

// Where appends a list predicates to the UserInfoUpdate builder.
func (_u *UserInfoUpdate) Where(ps ...predicate.UserInfo) *UserInfoUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserInfoUpdate) SetNickname(v string) *UserInfoUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserInfoUpdate) SetNillableNickname(v *string) *UserInfoUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserInfoUpdate) SetEmail(v string) *UserInfoUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserInfoUpdate) SetNillableEmail(v *string) *UserInfoUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserInfoUpdate) ClearEmail() *UserInfoUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *UserInfoUpdate) SetRawData(v []byte) *UserInfoUpdate {
	_u.mutation.SetRawData(v)
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *UserInfoUpdate) ClearRawData() *UserInfoUpdate {
	_u.mutation.ClearRawData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserInfoUpdate) SetUpdatedAt(v time.Time) *UserInfoUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserIdentityID sets the "user_identity" edge to the UserIdentity entity by ID.
func (_u *UserInfoUpdate) SetUserIdentityID(id int64) *UserInfoUpdate {
	_u.mutation.SetUserIdentityID(id)
	return _u
}

// SetUserIdentity sets the "user_identity" edge to the UserIdentity entity.
func (_u *UserInfoUpdate) SetUserIdentity(v *UserIdentity) *UserInfoUpdate {
	return _u.SetUserIdentityID(v.ID)
}

// Mutation returns the UserInfoMutation object of the builder.
func (_u *UserInfoUpdate) Mutation() *UserInfoMutation {
	return _u.mutation
}

// ClearUserIdentity clears the "user_identity" edge to the UserIdentity entity.
func (_u *UserInfoUpdate) ClearUserIdentity() *UserInfoUpdate {
	_u.mutation.ClearUserIdentity()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserInfoUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserInfoUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserInfoUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserInfoUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userinfo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserInfoUpdate) check() error {
	if v, ok := _u.mutation.Nickname(); ok {
		if err := userinfo.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "UserInfo.nickname": %w`, err)}
		}
	}
	if _u.mutation.UserIdentityCleared() && len(_u.mutation.UserIdentityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserInfo.user_identity"`)
	}
	return nil
}

func (_u *UserInfoUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userinfo.Table, userinfo.Columns, sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(userinfo.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(userinfo.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(userinfo.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(userinfo.FieldRawData, field.TypeBytes, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(userinfo.FieldRawData, field.TypeBytes)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserIdentityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userinfo.UserIdentityTable,
			Columns: []string{userinfo.UserIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userinfo.UserIdentityTable,
			Columns: []string{userinfo.UserIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserInfoUpdateOne is the builder for updating a single UserInfo entity.
type UserInfoUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserInfoMutation
}

// SetNickname sets the "nickname" field.
func (_u *UserInfoUpdateOne) SetNickname(v string) *UserInfoUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserInfoUpdateOne) SetNillableNickname(v *string) *UserInfoUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserInfoUpdateOne) SetEmail(v string) *UserInfoUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserInfoUpdateOne) SetNillableEmail(v *string) *UserInfoUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserInfoUpdateOne) ClearEmail() *UserInfoUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetRawData sets the "raw_data" field.
func (_u *UserInfoUpdateOne) SetRawData(v []byte) *UserInfoUpdateOne {
	_u.mutation.SetRawData(v)
	return _u
}

// ClearRawData clears the value of the "raw_data" field.
func (_u *UserInfoUpdateOne) ClearRawData() *UserInfoUpdateOne {
	_u.mutation.ClearRawData()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserInfoUpdateOne) SetUpdatedAt(v time.Time) *UserInfoUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserIdentityID sets the "user_identity" edge to the UserIdentity entity by ID.
func (_u *UserInfoUpdateOne) SetUserIdentityID(id int64) *UserInfoUpdateOne {
	_u.mutation.SetUserIdentityID(id)
	return _u
}

// SetUserIdentity sets the "user_identity" edge to the UserIdentity entity.
func (_u *UserInfoUpdateOne) SetUserIdentity(v *UserIdentity) *UserInfoUpdateOne {
	return _u.SetUserIdentityID(v.ID)
}

// Mutation returns the UserInfoMutation object of the builder.
func (_u *UserInfoUpdateOne) Mutation() *UserInfoMutation {
	return _u.mutation
}

// ClearUserIdentity clears the "user_identity" edge to the UserIdentity entity.
func (_u *UserInfoUpdateOne) ClearUserIdentity() *UserInfoUpdateOne {
	_u.mutation.ClearUserIdentity()
	return _u
}

// Where appends a list predicates to the UserInfoUpdate builder.
func (_u *UserInfoUpdateOne) Where(ps ...predicate.UserInfo) *UserInfoUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserInfoUpdateOne) Select(field string, fields ...string) *UserInfoUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserInfo entity.
func (_u *UserInfoUpdateOne) Save(ctx context.Context) (*UserInfo, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserInfoUpdateOne) SaveX(ctx context.Context) *UserInfo {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserInfoUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserInfoUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := userinfo.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserInfoUpdateOne) check() error {
	if v, ok := _u.mutation.Nickname(); ok {
		if err := userinfo.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "UserInfo.nickname": %w`, err)}
		}
	}
	if _u.mutation.UserIdentityCleared() && len(_u.mutation.UserIdentityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserInfo.user_identity"`)
	}
	return nil
}

func (_u *UserInfoUpdateOne) sqlSave(ctx context.Context) (_node *UserInfo, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userinfo.Table, userinfo.Columns, sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserInfo.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userinfo.FieldID)
		for _, f := range fields {
			if !userinfo.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userinfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(userinfo.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(userinfo.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(userinfo.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.RawData(); ok {
		_spec.SetField(userinfo.FieldRawData, field.TypeBytes, value)
	}
	if _u.mutation.RawDataCleared() {
		_spec.ClearField(userinfo.FieldRawData, field.TypeBytes)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(userinfo.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserIdentityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userinfo.UserIdentityTable,
			Columns: []string{userinfo.UserIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userinfo.UserIdentityTable,
			Columns: []string{userinfo.UserIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserInfo{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userinfo.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
