// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-com/serengeti/ent/predicate"
	"github.com/mandacode-com/serengeti/ent/service"
	"github.com/mandacode-com/serengeti/ent/useridentity"
	"github.com/mandacode-com/serengeti/ent/userinfo"
	"github.com/mandacode-com/serengeti/internal/domain/shared"
)

// UserIdentityUpdate is the builder for updating UserIdentity entities.
type UserIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *UserIdentityMutation
}

// Where appends a list predicates to the UserIdentityUpdate builder.
func (_u *UserIdentityUpdate) Where(ps ...predicate.UserIdentity) *UserIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServiceID sets the "service_id" field.
func (_u *UserIdentityUpdate) SetServiceID(v int64) *UserIdentityUpdate {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableServiceID(v *int64) *UserIdentityUpdate {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *UserIdentityUpdate) SetPublicID(v uuid.UUID) *UserIdentityUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillablePublicID(v *uuid.UUID) *UserIdentityUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UserIdentityUpdate) SetProviderID(v string) *UserIdentityUpdate {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableProviderID(v *string) *UserIdentityUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserIdentityUpdate) SetProvider(v shared.Provider) *UserIdentityUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableProvider(v *shared.Provider) *UserIdentityUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserIdentityUpdate) SetUpdatedAt(v time.Time) *UserIdentityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *UserIdentityUpdate) SetService(v *Service) *UserIdentityUpdate {
	return _u.SetServiceID(v.ID)
}

// SetUserInfoID sets the "user_info" edge to the UserInfo entity by ID.
func (_u *UserIdentityUpdate) SetUserInfoID(id int64) *UserIdentityUpdate {
	_u.mutation.SetUserInfoID(id)
	return _u
}

// SetNillableUserInfoID sets the "user_info" edge to the UserInfo entity by ID if the given value is not nil.
func (_u *UserIdentityUpdate) SetNillableUserInfoID(id *int64) *UserIdentityUpdate {
	if id != nil {
		_u = _u.SetUserInfoID(*id)
	}
	return _u
}

// SetUserInfo sets the "user_info" edge to the UserInfo entity.
func (_u *UserIdentityUpdate) SetUserInfo(v *UserInfo) *UserIdentityUpdate {
	return _u.SetUserInfoID(v.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (_u *UserIdentityUpdate) Mutation() *UserIdentityMutation {
	return _u.mutation
}

// ClearService clears the "service" edge to the Service entity.
func (_u *UserIdentityUpdate) ClearService() *UserIdentityUpdate {
	_u.mutation.ClearService()
	return _u
}

// ClearUserInfo clears the "user_info" edge to the UserInfo entity.
func (_u *UserIdentityUpdate) ClearUserInfo() *UserIdentityUpdate {
	_u.mutation.ClearUserInfo()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserIdentityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserIdentityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useridentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserIdentityUpdate) check() error {
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := useridentity.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := useridentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider": %w`, err)}
		}
	}
	if _u.mutation.ServiceCleared() && len(_u.mutation.ServiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserIdentity.service"`)
	}
	return nil
}

func (_u *UserIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useridentity.Table, useridentity.Columns, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(useridentity.FieldPublicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(useridentity.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.ServiceTable,
			Columns: []string{useridentity.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.ServiceTable,
			Columns: []string{useridentity.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   useridentity.UserInfoTable,
			Columns: []string{useridentity.UserInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   useridentity.UserInfoTable,
			Columns: []string{useridentity.UserInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useridentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserIdentityUpdateOne is the builder for updating a single UserIdentity entity.
type UserIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserIdentityMutation
}

// SetServiceID sets the "service_id" field.
func (_u *UserIdentityUpdateOne) SetServiceID(v int64) *UserIdentityUpdateOne {
	_u.mutation.SetServiceID(v)
	return _u
}

// SetNillableServiceID sets the "service_id" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableServiceID(v *int64) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetServiceID(*v)
	}
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *UserIdentityUpdateOne) SetPublicID(v uuid.UUID) *UserIdentityUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillablePublicID(v *uuid.UUID) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UserIdentityUpdateOne) SetProviderID(v string) *UserIdentityUpdateOne {
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableProviderID(v *string) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserIdentityUpdateOne) SetProvider(v shared.Provider) *UserIdentityUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableProvider(v *shared.Provider) *UserIdentityUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserIdentityUpdateOne) SetUpdatedAt(v time.Time) *UserIdentityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetService sets the "service" edge to the Service entity.
func (_u *UserIdentityUpdateOne) SetService(v *Service) *UserIdentityUpdateOne {
	return _u.SetServiceID(v.ID)
}

// SetUserInfoID sets the "user_info" edge to the UserInfo entity by ID.
func (_u *UserIdentityUpdateOne) SetUserInfoID(id int64) *UserIdentityUpdateOne {
	_u.mutation.SetUserInfoID(id)
	return _u
}

// SetNillableUserInfoID sets the "user_info" edge to the UserInfo entity by ID if the given value is not nil.
func (_u *UserIdentityUpdateOne) SetNillableUserInfoID(id *int64) *UserIdentityUpdateOne {
	if id != nil {
		_u = _u.SetUserInfoID(*id)
	}
	return _u
}

// SetUserInfo sets the "user_info" edge to the UserInfo entity.
func (_u *UserIdentityUpdateOne) SetUserInfo(v *UserInfo) *UserIdentityUpdateOne {
	return _u.SetUserInfoID(v.ID)
}

// Mutation returns the UserIdentityMutation object of the builder.
func (_u *UserIdentityUpdateOne) Mutation() *UserIdentityMutation {
	return _u.mutation
}

// ClearService clears the "service" edge to the Service entity.
func (_u *UserIdentityUpdateOne) ClearService() *UserIdentityUpdateOne {
	_u.mutation.ClearService()
	return _u
}

// ClearUserInfo clears the "user_info" edge to the UserInfo entity.
func (_u *UserIdentityUpdateOne) ClearUserInfo() *UserIdentityUpdateOne {
	_u.mutation.ClearUserInfo()
	return _u
}

// Where appends a list predicates to the UserIdentityUpdate builder.
func (_u *UserIdentityUpdateOne) Where(ps ...predicate.UserIdentity) *UserIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserIdentityUpdateOne) Select(field string, fields ...string) *UserIdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserIdentity entity.
func (_u *UserIdentityUpdateOne) Save(ctx context.Context) (*UserIdentity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserIdentityUpdateOne) SaveX(ctx context.Context) *UserIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserIdentityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useridentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserIdentityUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderID(); ok {
		if err := useridentity.ProviderIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_id", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := useridentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserIdentity.provider": %w`, err)}
		}
	}
	if _u.mutation.ServiceCleared() && len(_u.mutation.ServiceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserIdentity.service"`)
	}
	return nil
}

func (_u *UserIdentityUpdateOne) sqlSave(ctx context.Context) (_node *UserIdentity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useridentity.Table, useridentity.Columns, sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useridentity.FieldID)
		for _, f := range fields {
			if !useridentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useridentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(useridentity.FieldPublicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(useridentity.FieldProviderID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(useridentity.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useridentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ServiceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.ServiceTable,
			Columns: []string{useridentity.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ServiceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useridentity.ServiceTable,
			Columns: []string{useridentity.ServiceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   useridentity.UserInfoTable,
			Columns: []string{useridentity.UserInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   useridentity.UserInfoTable,
			Columns: []string{useridentity.UserInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserIdentity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useridentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
