// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/mandacode-com/mandacode-ssam/ent/useridentity"
	"github.com/mandacode-com/mandacode-ssam/ent/userinfo"
)

// UserInfoCreate is the builder for creating a UserInfo entity.
type UserInfoCreate struct {
	config
	mutation *UserInfoMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (_c *UserInfoCreate) SetPublicID(v uuid.UUID) *UserInfoCreate {
	_c.mutation.SetPublicID(v)
	return _c
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_c *UserInfoCreate) SetNillablePublicID(v *uuid.UUID) *UserInfoCreate {
	if v != nil {
		_c.SetPublicID(*v)
	}
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *UserInfoCreate) SetNickname(v string) *UserInfoCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserInfoCreate) SetEmail(v string) *UserInfoCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetRawData sets the "raw_data" field.
func (_c *UserInfoCreate) SetRawData(v []byte) *UserInfoCreate {
	_c.mutation.SetRawData(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserInfoCreate) SetCreatedAt(v time.Time) *UserInfoCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserInfoCreate) SetNillableCreatedAt(v *time.Time) *UserInfoCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserInfoCreate) SetUpdatedAt(v time.Time) *UserInfoCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserInfoCreate) SetNillableUpdatedAt(v *time.Time) *UserInfoCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserInfoCreate) SetID(v int64) *UserInfoCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserIdentityID sets the "user_identity" edge to the UserIdentity entity by ID.
func (_c *UserInfoCreate) SetUserIdentityID(id int64) *UserInfoCreate {
	_c.mutation.SetUserIdentityID(id)
	return _c
}

// SetUserIdentity sets the "user_identity" edge to the UserIdentity entity.
func (_c *UserInfoCreate) SetUserIdentity(v *UserIdentity) *UserInfoCreate {
	return _c.SetUserIdentityID(v.ID)
}

// Mutation returns the UserInfoMutation object of the builder.
func (_c *UserInfoCreate) Mutation() *UserInfoMutation {
	return _c.mutation
}

// Save creates the UserInfo in the database.
func (_c *UserInfoCreate) Save(ctx context.Context) (*UserInfo, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserInfoCreate) SaveX(ctx context.Context) *UserInfo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserInfoCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserInfoCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserInfoCreate) defaults() {
	if _, ok := _c.mutation.PublicID(); !ok {
		v := userinfo.DefaultPublicID()
		_c.mutation.SetPublicID(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userinfo.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userinfo.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserInfoCreate) check() error {
	if _, ok := _c.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`ent: missing required field "UserInfo.public_id"`)}
	}
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "UserInfo.nickname"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := userinfo.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "UserInfo.nickname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "UserInfo.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := userinfo.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "UserInfo.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserInfo.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserInfo.updated_at"`)}
	}
	if len(_c.mutation.UserIdentityIDs()) == 0 {
		return &ValidationError{Name: "user_identity", err: errors.New(`ent: missing required edge "UserInfo.user_identity"`)}
	}
	return nil
}

func (_c *UserInfoCreate) sqlSave(ctx context.Context) (*UserInfo, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserInfoCreate) createSpec() (*UserInfo, *sqlgraph.CreateSpec) {
	var (
		_node = &UserInfo{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userinfo.Table, sqlgraph.NewFieldSpec(userinfo.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PublicID(); ok {
		_spec.SetField(userinfo.FieldPublicID, field.TypeUUID, value)
		_node.PublicID = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(userinfo.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(userinfo.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.RawData(); ok {
		_spec.SetField(userinfo.FieldRawData, field.TypeBytes, value)
		_node.RawData = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userinfo.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userinfo.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIdentityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   userinfo.UserIdentityTable,
			Columns: []string{userinfo.UserIdentityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useridentity.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_identity_user_info = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserInfoCreateBulk is the builder for creating many UserInfo entities in bulk.
type UserInfoCreateBulk struct {
	config
	err      error
	builders []*UserInfoCreate
}

// Save creates the UserInfo entities in the database.
func (_c *UserInfoCreateBulk) Save(ctx context.Context) ([]*UserInfo, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserInfo, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserInfoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserInfoCreateBulk) SaveX(ctx context.Context) []*UserInfo {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserInfoCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserInfoCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
