// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-com/serengeti/ent/clientapp"
	"github.com/mandacode-com/serengeti/ent/weboauth"
	"github.com/mandacode-com/serengeti/internal/domain/shared"
)

// WebOAuthCreate is the builder for creating a WebOAuth entity.
type WebOAuthCreate struct {
	config
	mutation *WebOAuthMutation
	hooks    []Hook
}

// SetClientAppID sets the "client_app_id" field.
func (_c *WebOAuthCreate) SetClientAppID(v int64) *WebOAuthCreate {
	_c.mutation.SetClientAppID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *WebOAuthCreate) SetProvider(v shared.Provider) *WebOAuthCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetOauthClientID sets the "oauth_client_id" field.
func (_c *WebOAuthCreate) SetOauthClientID(v string) *WebOAuthCreate {
	_c.mutation.SetOauthClientID(v)
	return _c
}

// SetOauthSecretCt sets the "oauth_secret_ct" field.
func (_c *WebOAuthCreate) SetOauthSecretCt(v []byte) *WebOAuthCreate {
	_c.mutation.SetOauthSecretCt(v)
	return _c
}

// SetOauthSecretNonce sets the "oauth_secret_nonce" field.
func (_c *WebOAuthCreate) SetOauthSecretNonce(v []byte) *WebOAuthCreate {
	_c.mutation.SetOauthSecretNonce(v)
	return _c
}

// SetDekWrapped sets the "dek_wrapped" field.
func (_c *WebOAuthCreate) SetDekWrapped(v []byte) *WebOAuthCreate {
	_c.mutation.SetDekWrapped(v)
	return _c
}

// SetDekNonce sets the "dek_nonce" field.
func (_c *WebOAuthCreate) SetDekNonce(v []byte) *WebOAuthCreate {
	_c.mutation.SetDekNonce(v)
	return _c
}

// SetDekRotatedAt sets the "dek_rotated_at" field.
func (_c *WebOAuthCreate) SetDekRotatedAt(v time.Time) *WebOAuthCreate {
	_c.mutation.SetDekRotatedAt(v)
	return _c
}

// SetNillableDekRotatedAt sets the "dek_rotated_at" field if the given value is not nil.
func (_c *WebOAuthCreate) SetNillableDekRotatedAt(v *time.Time) *WebOAuthCreate {
	if v != nil {
		_c.SetDekRotatedAt(*v)
	}
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *WebOAuthCreate) SetRedirectURI(v string) *WebOAuthCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_c *WebOAuthCreate) SetNillableRedirectURI(v *string) *WebOAuthCreate {
	if v != nil {
		_c.SetRedirectURI(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *WebOAuthCreate) SetScopes(v []string) *WebOAuthCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebOAuthCreate) SetCreatedAt(v time.Time) *WebOAuthCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebOAuthCreate) SetNillableCreatedAt(v *time.Time) *WebOAuthCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *WebOAuthCreate) SetUpdatedAt(v time.Time) *WebOAuthCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *WebOAuthCreate) SetNillableUpdatedAt(v *time.Time) *WebOAuthCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *WebOAuthCreate) SetID(v int64) *WebOAuthCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetClientApp sets the "client_app" edge to the ClientApp entity.
func (_c *WebOAuthCreate) SetClientApp(v *ClientApp) *WebOAuthCreate {
	return _c.SetClientAppID(v.ID)
}

// Mutation returns the WebOAuthMutation object of the builder.
func (_c *WebOAuthCreate) Mutation() *WebOAuthMutation {
	return _c.mutation
}

// Save creates the WebOAuth in the database.
func (_c *WebOAuthCreate) Save(ctx context.Context) (*WebOAuth, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebOAuthCreate) SaveX(ctx context.Context) *WebOAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebOAuthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebOAuthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebOAuthCreate) defaults() {
	if _, ok := _c.mutation.DekRotatedAt(); !ok {
		v := weboauth.DefaultDekRotatedAt()
		_c.mutation.SetDekRotatedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := weboauth.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := weboauth.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebOAuthCreate) check() error {
	if _, ok := _c.mutation.ClientAppID(); !ok {
		return &ValidationError{Name: "client_app_id", err: errors.New(`ent: missing required field "WebOAuth.client_app_id"`)}
	}
	if v, ok := _c.mutation.ClientAppID(); ok {
		if err := weboauth.ClientAppIDValidator(v); err != nil {
			return &ValidationError{Name: "client_app_id", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.client_app_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "WebOAuth.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := weboauth.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OauthClientID(); !ok {
		return &ValidationError{Name: "oauth_client_id", err: errors.New(`ent: missing required field "WebOAuth.oauth_client_id"`)}
	}
	if v, ok := _c.mutation.OauthClientID(); ok {
		if err := weboauth.OauthClientIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_client_id", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OauthSecretCt(); !ok {
		return &ValidationError{Name: "oauth_secret_ct", err: errors.New(`ent: missing required field "WebOAuth.oauth_secret_ct"`)}
	}
	if v, ok := _c.mutation.OauthSecretCt(); ok {
		if err := weboauth.OauthSecretCtValidator(v); err != nil {
			return &ValidationError{Name: "oauth_secret_ct", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_secret_ct": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OauthSecretNonce(); !ok {
		return &ValidationError{Name: "oauth_secret_nonce", err: errors.New(`ent: missing required field "WebOAuth.oauth_secret_nonce"`)}
	}
	if v, ok := _c.mutation.OauthSecretNonce(); ok {
		if err := weboauth.OauthSecretNonceValidator(v); err != nil {
			return &ValidationError{Name: "oauth_secret_nonce", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_secret_nonce": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DekWrapped(); !ok {
		return &ValidationError{Name: "dek_wrapped", err: errors.New(`ent: missing required field "WebOAuth.dek_wrapped"`)}
	}
	if v, ok := _c.mutation.DekWrapped(); ok {
		if err := weboauth.DekWrappedValidator(v); err != nil {
			return &ValidationError{Name: "dek_wrapped", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.dek_wrapped": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DekNonce(); !ok {
		return &ValidationError{Name: "dek_nonce", err: errors.New(`ent: missing required field "WebOAuth.dek_nonce"`)}
	}
	if v, ok := _c.mutation.DekNonce(); ok {
		if err := weboauth.DekNonceValidator(v); err != nil {
			return &ValidationError{Name: "dek_nonce", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.dek_nonce": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DekRotatedAt(); !ok {
		return &ValidationError{Name: "dek_rotated_at", err: errors.New(`ent: missing required field "WebOAuth.dek_rotated_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WebOAuth.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WebOAuth.updated_at"`)}
	}
	if len(_c.mutation.ClientAppIDs()) == 0 {
		return &ValidationError{Name: "client_app", err: errors.New(`ent: missing required edge "WebOAuth.client_app"`)}
	}
	return nil
}

func (_c *WebOAuthCreate) sqlSave(ctx context.Context) (*WebOAuth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebOAuthCreate) createSpec() (*WebOAuth, *sqlgraph.CreateSpec) {
	var (
		_node = &WebOAuth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(weboauth.Table, sqlgraph.NewFieldSpec(weboauth.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(weboauth.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.OauthClientID(); ok {
		_spec.SetField(weboauth.FieldOauthClientID, field.TypeString, value)
		_node.OauthClientID = value
	}
	if value, ok := _c.mutation.OauthSecretCt(); ok {
		_spec.SetField(weboauth.FieldOauthSecretCt, field.TypeBytes, value)
		_node.OauthSecretCt = value
	}
	if value, ok := _c.mutation.OauthSecretNonce(); ok {
		_spec.SetField(weboauth.FieldOauthSecretNonce, field.TypeBytes, value)
		_node.OauthSecretNonce = value
	}
	if value, ok := _c.mutation.DekWrapped(); ok {
		_spec.SetField(weboauth.FieldDekWrapped, field.TypeBytes, value)
		_node.DekWrapped = value
	}
	if value, ok := _c.mutation.DekNonce(); ok {
		_spec.SetField(weboauth.FieldDekNonce, field.TypeBytes, value)
		_node.DekNonce = value
	}
	if value, ok := _c.mutation.DekRotatedAt(); ok {
		_spec.SetField(weboauth.FieldDekRotatedAt, field.TypeTime, value)
		_node.DekRotatedAt = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(weboauth.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(weboauth.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(weboauth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(weboauth.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ClientAppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   weboauth.ClientAppTable,
			Columns: []string{weboauth.ClientAppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ClientAppID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WebOAuthCreateBulk is the builder for creating many WebOAuth entities in bulk.
type WebOAuthCreateBulk struct {
	config
	err      error
	builders []*WebOAuthCreate
}

// Save creates the WebOAuth entities in the database.
func (_c *WebOAuthCreateBulk) Save(ctx context.Context) ([]*WebOAuth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebOAuth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebOAuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebOAuthCreateBulk) SaveX(ctx context.Context) []*WebOAuth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebOAuthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebOAuthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
