// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/mandacode-com/serengeti-integrated/ent/clientapp"
	"github.com/mandacode-com/serengeti-integrated/ent/predicate"
	"github.com/mandacode-com/serengeti-integrated/ent/weboauth"
	"github.com/mandacode-com/serengeti-integrated/internal/domain/shared"
)

// WebOAuthUpdate is the builder for updating WebOAuth entities.
type WebOAuthUpdate struct {
	config
	hooks    []Hook
	mutation *WebOAuthMutation
}

// Where appends a list predicates to the WebOAuthUpdate builder.
func (_u *WebOAuthUpdate) Where(ps ...predicate.WebOAuth) *WebOAuthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientAppID sets the "client_app_id" field.
func (_u *WebOAuthUpdate) SetClientAppID(v int64) *WebOAuthUpdate {
	_u.mutation.SetClientAppID(v)
	return _u
}

// SetNillableClientAppID sets the "client_app_id" field if the given value is not nil.
func (_u *WebOAuthUpdate) SetNillableClientAppID(v *int64) *WebOAuthUpdate {
	if v != nil {
		_u.SetClientAppID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *WebOAuthUpdate) SetProvider(v shared.Provider) *WebOAuthUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *WebOAuthUpdate) SetNillableProvider(v *shared.Provider) *WebOAuthUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOauthClientID sets the "oauth_client_id" field.
func (_u *WebOAuthUpdate) SetOauthClientID(v string) *WebOAuthUpdate {
	_u.mutation.SetOauthClientID(v)
	return _u
}

// SetNillableOauthClientID sets the "oauth_client_id" field if the given value is not nil.
func (_u *WebOAuthUpdate) SetNillableOauthClientID(v *string) *WebOAuthUpdate {
	if v != nil {
		_u.SetOauthClientID(*v)
	}
	return _u
}

// SetOauthSecretCt sets the "oauth_secret_ct" field.
func (_u *WebOAuthUpdate) SetOauthSecretCt(v []byte) *WebOAuthUpdate {
	_u.mutation.SetOauthSecretCt(v)
	return _u
}

// SetOauthSecretNonce sets the "oauth_secret_nonce" field.
func (_u *WebOAuthUpdate) SetOauthSecretNonce(v []byte) *WebOAuthUpdate {
	_u.mutation.SetOauthSecretNonce(v)
	return _u
}

// SetDekWrapped sets the "dek_wrapped" field.
func (_u *WebOAuthUpdate) SetDekWrapped(v []byte) *WebOAuthUpdate {
	_u.mutation.SetDekWrapped(v)
	return _u
}

// SetDekNonce sets the "dek_nonce" field.
func (_u *WebOAuthUpdate) SetDekNonce(v []byte) *WebOAuthUpdate {
	_u.mutation.SetDekNonce(v)
	return _u
}

// SetDekRotatedAt sets the "dek_rotated_at" field.
func (_u *WebOAuthUpdate) SetDekRotatedAt(v time.Time) *WebOAuthUpdate {
	_u.mutation.SetDekRotatedAt(v)
	return _u
}

// SetNillableDekRotatedAt sets the "dek_rotated_at" field if the given value is not nil.
func (_u *WebOAuthUpdate) SetNillableDekRotatedAt(v *time.Time) *WebOAuthUpdate {
	if v != nil {
		_u.SetDekRotatedAt(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *WebOAuthUpdate) SetRedirectURI(v string) *WebOAuthUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *WebOAuthUpdate) SetNillableRedirectURI(v *string) *WebOAuthUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (_u *WebOAuthUpdate) ClearRedirectURI() *WebOAuthUpdate {
	_u.mutation.ClearRedirectURI()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *WebOAuthUpdate) SetScopes(v []string) *WebOAuthUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *WebOAuthUpdate) AppendScopes(v []string) *WebOAuthUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *WebOAuthUpdate) ClearScopes() *WebOAuthUpdate {
	_u.mutation.ClearScopes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebOAuthUpdate) SetUpdatedAt(v time.Time) *WebOAuthUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientApp sets the "client_app" edge to the ClientApp entity.
func (_u *WebOAuthUpdate) SetClientApp(v *ClientApp) *WebOAuthUpdate {
	return _u.SetClientAppID(v.ID)
}

// Mutation returns the WebOAuthMutation object of the builder.
func (_u *WebOAuthUpdate) Mutation() *WebOAuthMutation {
	return _u.mutation
}

// ClearClientApp clears the "client_app" edge to the ClientApp entity.
func (_u *WebOAuthUpdate) ClearClientApp() *WebOAuthUpdate {
	_u.mutation.ClearClientApp()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebOAuthUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebOAuthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebOAuthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebOAuthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebOAuthUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := weboauth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebOAuthUpdate) check() error {
	if v, ok := _u.mutation.ClientAppID(); ok {
		if err := weboauth.ClientAppIDValidator(v); err != nil {
			return &ValidationError{Name: "client_app_id", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.client_app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := weboauth.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthClientID(); ok {
		if err := weboauth.OauthClientIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_client_id", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthSecretCt(); ok {
		if err := weboauth.OauthSecretCtValidator(v); err != nil {
			return &ValidationError{Name: "oauth_secret_ct", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_secret_ct": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthSecretNonce(); ok {
		if err := weboauth.OauthSecretNonceValidator(v); err != nil {
			return &ValidationError{Name: "oauth_secret_nonce", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_secret_nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DekWrapped(); ok {
		if err := weboauth.DekWrappedValidator(v); err != nil {
			return &ValidationError{Name: "dek_wrapped", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.dek_wrapped": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DekNonce(); ok {
		if err := weboauth.DekNonceValidator(v); err != nil {
			return &ValidationError{Name: "dek_nonce", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.dek_nonce": %w`, err)}
		}
	}
	if _u.mutation.ClientAppCleared() && len(_u.mutation.ClientAppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebOAuth.client_app"`)
	}
	return nil
}

func (_u *WebOAuthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(weboauth.Table, weboauth.Columns, sqlgraph.NewFieldSpec(weboauth.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(weboauth.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OauthClientID(); ok {
		_spec.SetField(weboauth.FieldOauthClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthSecretCt(); ok {
		_spec.SetField(weboauth.FieldOauthSecretCt, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.OauthSecretNonce(); ok {
		_spec.SetField(weboauth.FieldOauthSecretNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DekWrapped(); ok {
		_spec.SetField(weboauth.FieldDekWrapped, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DekNonce(); ok {
		_spec.SetField(weboauth.FieldDekNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DekRotatedAt(); ok {
		_spec.SetField(weboauth.FieldDekRotatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(weboauth.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.RedirectURICleared() {
		_spec.ClearField(weboauth.FieldRedirectURI, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(weboauth.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, weboauth.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(weboauth.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(weboauth.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClientAppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   weboauth.ClientAppTable,
			Columns: []string{weboauth.ClientAppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientAppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   weboauth.ClientAppTable,
			Columns: []string{weboauth.ClientAppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{weboauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebOAuthUpdateOne is the builder for updating a single WebOAuth entity.
type WebOAuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebOAuthMutation
}

// SetClientAppID sets the "client_app_id" field.
func (_u *WebOAuthUpdateOne) SetClientAppID(v int64) *WebOAuthUpdateOne {
	_u.mutation.SetClientAppID(v)
	return _u
}

// SetNillableClientAppID sets the "client_app_id" field if the given value is not nil.
func (_u *WebOAuthUpdateOne) SetNillableClientAppID(v *int64) *WebOAuthUpdateOne {
	if v != nil {
		_u.SetClientAppID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *WebOAuthUpdateOne) SetProvider(v shared.Provider) *WebOAuthUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *WebOAuthUpdateOne) SetNillableProvider(v *shared.Provider) *WebOAuthUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetOauthClientID sets the "oauth_client_id" field.
func (_u *WebOAuthUpdateOne) SetOauthClientID(v string) *WebOAuthUpdateOne {
	_u.mutation.SetOauthClientID(v)
	return _u
}

// SetNillableOauthClientID sets the "oauth_client_id" field if the given value is not nil.
func (_u *WebOAuthUpdateOne) SetNillableOauthClientID(v *string) *WebOAuthUpdateOne {
	if v != nil {
		_u.SetOauthClientID(*v)
	}
	return _u
}

// SetOauthSecretCt sets the "oauth_secret_ct" field.
func (_u *WebOAuthUpdateOne) SetOauthSecretCt(v []byte) *WebOAuthUpdateOne {
	_u.mutation.SetOauthSecretCt(v)
	return _u
}

// SetOauthSecretNonce sets the "oauth_secret_nonce" field.
func (_u *WebOAuthUpdateOne) SetOauthSecretNonce(v []byte) *WebOAuthUpdateOne {
	_u.mutation.SetOauthSecretNonce(v)
	return _u
}

// SetDekWrapped sets the "dek_wrapped" field.
func (_u *WebOAuthUpdateOne) SetDekWrapped(v []byte) *WebOAuthUpdateOne {
	_u.mutation.SetDekWrapped(v)
	return _u
}

// SetDekNonce sets the "dek_nonce" field.
func (_u *WebOAuthUpdateOne) SetDekNonce(v []byte) *WebOAuthUpdateOne {
	_u.mutation.SetDekNonce(v)
	return _u
}

// SetDekRotatedAt sets the "dek_rotated_at" field.
func (_u *WebOAuthUpdateOne) SetDekRotatedAt(v time.Time) *WebOAuthUpdateOne {
	_u.mutation.SetDekRotatedAt(v)
	return _u
}

// SetNillableDekRotatedAt sets the "dek_rotated_at" field if the given value is not nil.
func (_u *WebOAuthUpdateOne) SetNillableDekRotatedAt(v *time.Time) *WebOAuthUpdateOne {
	if v != nil {
		_u.SetDekRotatedAt(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *WebOAuthUpdateOne) SetRedirectURI(v string) *WebOAuthUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *WebOAuthUpdateOne) SetNillableRedirectURI(v *string) *WebOAuthUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// ClearRedirectURI clears the value of the "redirect_uri" field.
func (_u *WebOAuthUpdateOne) ClearRedirectURI() *WebOAuthUpdateOne {
	_u.mutation.ClearRedirectURI()
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *WebOAuthUpdateOne) SetScopes(v []string) *WebOAuthUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *WebOAuthUpdateOne) AppendScopes(v []string) *WebOAuthUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// ClearScopes clears the value of the "scopes" field.
func (_u *WebOAuthUpdateOne) ClearScopes() *WebOAuthUpdateOne {
	_u.mutation.ClearScopes()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebOAuthUpdateOne) SetUpdatedAt(v time.Time) *WebOAuthUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClientApp sets the "client_app" edge to the ClientApp entity.
func (_u *WebOAuthUpdateOne) SetClientApp(v *ClientApp) *WebOAuthUpdateOne {
	return _u.SetClientAppID(v.ID)
}

// Mutation returns the WebOAuthMutation object of the builder.
func (_u *WebOAuthUpdateOne) Mutation() *WebOAuthMutation {
	return _u.mutation
}

// ClearClientApp clears the "client_app" edge to the ClientApp entity.
func (_u *WebOAuthUpdateOne) ClearClientApp() *WebOAuthUpdateOne {
	_u.mutation.ClearClientApp()
	return _u
}

// Where appends a list predicates to the WebOAuthUpdate builder.
func (_u *WebOAuthUpdateOne) Where(ps ...predicate.WebOAuth) *WebOAuthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebOAuthUpdateOne) Select(field string, fields ...string) *WebOAuthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebOAuth entity.
func (_u *WebOAuthUpdateOne) Save(ctx context.Context) (*WebOAuth, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebOAuthUpdateOne) SaveX(ctx context.Context) *WebOAuth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebOAuthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebOAuthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WebOAuthUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := weboauth.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WebOAuthUpdateOne) check() error {
	if v, ok := _u.mutation.ClientAppID(); ok {
		if err := weboauth.ClientAppIDValidator(v); err != nil {
			return &ValidationError{Name: "client_app_id", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.client_app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := weboauth.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthClientID(); ok {
		if err := weboauth.OauthClientIDValidator(v); err != nil {
			return &ValidationError{Name: "oauth_client_id", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthSecretCt(); ok {
		if err := weboauth.OauthSecretCtValidator(v); err != nil {
			return &ValidationError{Name: "oauth_secret_ct", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_secret_ct": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OauthSecretNonce(); ok {
		if err := weboauth.OauthSecretNonceValidator(v); err != nil {
			return &ValidationError{Name: "oauth_secret_nonce", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.oauth_secret_nonce": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DekWrapped(); ok {
		if err := weboauth.DekWrappedValidator(v); err != nil {
			return &ValidationError{Name: "dek_wrapped", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.dek_wrapped": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DekNonce(); ok {
		if err := weboauth.DekNonceValidator(v); err != nil {
			return &ValidationError{Name: "dek_nonce", err: fmt.Errorf(`ent: validator failed for field "WebOAuth.dek_nonce": %w`, err)}
		}
	}
	if _u.mutation.ClientAppCleared() && len(_u.mutation.ClientAppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "WebOAuth.client_app"`)
	}
	return nil
}

func (_u *WebOAuthUpdateOne) sqlSave(ctx context.Context) (_node *WebOAuth, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(weboauth.Table, weboauth.Columns, sqlgraph.NewFieldSpec(weboauth.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebOAuth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, weboauth.FieldID)
		for _, f := range fields {
			if !weboauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != weboauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(weboauth.FieldProvider, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OauthClientID(); ok {
		_spec.SetField(weboauth.FieldOauthClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.OauthSecretCt(); ok {
		_spec.SetField(weboauth.FieldOauthSecretCt, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.OauthSecretNonce(); ok {
		_spec.SetField(weboauth.FieldOauthSecretNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DekWrapped(); ok {
		_spec.SetField(weboauth.FieldDekWrapped, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DekNonce(); ok {
		_spec.SetField(weboauth.FieldDekNonce, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.DekRotatedAt(); ok {
		_spec.SetField(weboauth.FieldDekRotatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(weboauth.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.RedirectURICleared() {
		_spec.ClearField(weboauth.FieldRedirectURI, field.TypeString)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(weboauth.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, weboauth.FieldScopes, value)
		})
	}
	if _u.mutation.ScopesCleared() {
		_spec.ClearField(weboauth.FieldScopes, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(weboauth.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ClientAppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   weboauth.ClientAppTable,
			Columns: []string{weboauth.ClientAppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClientAppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   weboauth.ClientAppTable,
			Columns: []string{weboauth.ClientAppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clientapp.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WebOAuth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{weboauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
