{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mc-pms.fullname" . }}-db
  labels:
    {{- include "mc-pms.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.user | required "database.user is required when database.existingSecret is not set" | quote }}
  password: {{ .Values.database.password | required "database.password is required when database.existingSecret is not set" | quote }}
{{- end }}
