// Code generated by ent, DO NOT EDIT.

package weboauth

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mandacode-com/mandacode-service-hub/internal/domain/shared"
)

const (
	// Label holds the string label denoting the weboauth type in the database.
	Label = "web_oauth"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldClientAppID holds the string denoting the client_app_id field in the database.
	FieldClientAppID = "client_app_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldOauthClientID holds the string denoting the oauth_client_id field in the database.
	FieldOauthClientID = "oauth_client_id"
	// FieldOauthSecretCt holds the string denoting the oauth_secret_ct field in the database.
	FieldOauthSecretCt = "oauth_secret_ct"
	// FieldOauthSecretNonce holds the string denoting the oauth_secret_nonce field in the database.
	FieldOauthSecretNonce = "oauth_secret_nonce"
	// FieldDekWrapped holds the string denoting the dek_wrapped field in the database.
	FieldDekWrapped = "dek_wrapped"
	// FieldDekNonce holds the string denoting the dek_nonce field in the database.
	FieldDekNonce = "dek_nonce"
	// FieldDekRotatedAt holds the string denoting the dek_rotated_at field in the database.
	FieldDekRotatedAt = "dek_rotated_at"
	// FieldRedirectURI holds the string denoting the redirect_uri field in the database.
	FieldRedirectURI = "redirect_uri"
	// FieldScopes holds the string denoting the scopes field in the database.
	FieldScopes = "scopes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeClientApp holds the string denoting the client_app edge name in mutations.
	EdgeClientApp = "client_app"
	// Table holds the table name of the weboauth in the database.
	Table = "web_oauths"
	// ClientAppTable is the table that holds the client_app relation/edge.
	ClientAppTable = "web_oauths"
	// ClientAppInverseTable is the table name for the ClientApp entity.
	// It exists in this package in order to avoid circular dependency with the "clientapp" package.
	ClientAppInverseTable = "client_apps"
	// ClientAppColumn is the table column denoting the client_app relation/edge.
	ClientAppColumn = "client_app_id"
)

// Columns holds all SQL columns for weboauth fields.
var Columns = []string{
	FieldID,
	FieldClientAppID,
	FieldProvider,
	FieldOauthClientID,
	FieldOauthSecretCt,
	FieldOauthSecretNonce,
	FieldDekWrapped,
	FieldDekNonce,
	FieldDekRotatedAt,
	FieldRedirectURI,
	FieldScopes,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ClientAppIDValidator is a validator for the "client_app_id" field. It is called by the builders before save.
	ClientAppIDValidator func(int64) error
	// OauthClientIDValidator is a validator for the "oauth_client_id" field. It is called by the builders before save.
	OauthClientIDValidator func(string) error
	// OauthSecretCtValidator is a validator for the "oauth_secret_ct" field. It is called by the builders before save.
	OauthSecretCtValidator func([]byte) error
	// OauthSecretNonceValidator is a validator for the "oauth_secret_nonce" field. It is called by the builders before save.
	OauthSecretNonceValidator func([]byte) error
	// DekWrappedValidator is a validator for the "dek_wrapped" field. It is called by the builders before save.
	DekWrappedValidator func([]byte) error
	// DekNonceValidator is a validator for the "dek_nonce" field. It is called by the builders before save.
	DekNonceValidator func([]byte) error
	// DefaultDekRotatedAt holds the default value on creation for the "dek_rotated_at" field.
	DefaultDekRotatedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// ProviderValidator is a validator for the "provider" field enum values. It is called by the builders before save.
func ProviderValidator(pr shared.Provider) error {
	switch pr {
	case "google", "apple":
		return nil
	default:
		return fmt.Errorf("weboauth: invalid enum value for provider field: %q", pr)
	}
}

// OrderOption defines the ordering options for the WebOAuth queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByClientAppID orders the results by the client_app_id field.
func ByClientAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientAppID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByOauthClientID orders the results by the oauth_client_id field.
func ByOauthClientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOauthClientID, opts...).ToFunc()
}

// ByDekRotatedAt orders the results by the dek_rotated_at field.
func ByDekRotatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDekRotatedAt, opts...).ToFunc()
}

// ByRedirectURI orders the results by the redirect_uri field.
func ByRedirectURI(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedirectURI, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByClientAppField orders the results by client_app field.
func ByClientAppField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newClientAppStep(), sql.OrderByField(field, opts...))
	}
}
func newClientAppStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ClientAppInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ClientAppTable, ClientAppColumn),
	)
}
