{{- if and .Values.auth.enabled .Values.auth.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "defined.fullname" . }}-auth
  labels:
    {{- include "defined.auth.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "defined.fullname" . }}-auth
  minReplicas: {{ .Values.auth.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.auth.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.auth.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.auth.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
