{{- if .Values.core.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defined.core.configMapName" . }}
  labels:
    {{- include "defined.core.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.global.env | default "prod" | quote }}
  PORT: {{ .Values.core.service.targetPort | quote }}
  READ_TIMEOUT: {{ .Values.core.server.readTimeout | quote }}
  WRITE_TIMEOUT: {{ .Values.core.server.writeTimeout | quote }}
{{- end }}
