{{- if .Values.core.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defined.fullname" . }}-core
  labels:
    {{- include "defined.core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.core.service.type }}
  ports:
    - port: {{ .Values.core.service.port }}
      targetPort: {{ .Values.core.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "defined.core.selectorLabels" . | nindent 4 }}
{{- end }}