{{- if .Values.management.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "defined.management.configMapName" . }}
  labels:
    {{- include "defined.management.labels" . | nindent 4 }}
data:
  ENV: {{ .Values.management.env | default "prod" | quote }}
  PORT: "8080"
  READ_TIMEOUT: {{ .Values.management.server.readTimeout | quote }}
  WRITE_TIMEOUT: {{ .Values.management.server.writeTimeout | quote }}
  READ_HEADER_TIMEOUT: {{ .Values.management.server.readHeaderTimeout | quote }}
  IDLE_TIMEOUT: {{ .Values.management.server.idleTimeout | quote }}
  IAM_ENABLED: {{ .Values.management.iam.enabled | quote }}
  IAM_SERVICE_URL: {{ .Values.management.iam.serviceUrl | quote }}
  ID_PREFIX_SERVICE: {{ .Values.management.prefix.service | quote }}
{{- end }}
