{{- if .Values.management.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "defined.fullname" . }}-management
  labels:
    {{- include "defined.management.labels" . | nindent 4 }}
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: {{ .Values.management.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "defined.management.selectorLabels" . | nindent 4 }}
{{- end }}
