-- Create "services" table
CREATE TABLE "public"."services" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "public_id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "service_name" to table: "services"
CREATE UNIQUE INDEX "service_name" ON "public"."services" ("name");
-- Create index "service_public_id" to table: "services"
CREATE UNIQUE INDEX "service_public_id" ON "public"."services" ("public_id");
-- Create index "services_public_id_key" to table: "services"
CREATE UNIQUE INDEX "services_public_id_key" ON "public"."services" ("public_id");
-- Create "client_apps" table
CREATE TABLE "public"."client_apps" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "public_id" uuid NOT NULL,
  "secret_hash" bytea NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "service_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "client_apps_services_client_apps" FOREIGN KEY ("service_id") REFERENCES "public"."services" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "client_apps_public_id_key" to table: "client_apps"
CREATE UNIQUE INDEX "client_apps_public_id_key" ON "public"."client_apps" ("public_id");
-- Create index "clientapp_public_id" to table: "client_apps"
CREATE UNIQUE INDEX "clientapp_public_id" ON "public"."client_apps" ("public_id");
-- Create index "clientapp_service_id_name" to table: "client_apps"
CREATE UNIQUE INDEX "clientapp_service_id_name" ON "public"."client_apps" ("service_id", "name");
