{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "defined.databaseSecretName" . }}
  labels:
    {{- include "defined.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- $username := .Values.database.auth.username }}
  {{- $password := .Values.database.auth.password }}
  {{- $host := .Values.database.host }}
  {{- $port := .Values.database.port | default 5432 | int }}
  {{- $dbName := .Values.database.dbName }}
  {{- $sslMode := .Values.database.sslMode | default "disable" }}
  {{- $migUsername := .Values.database.migration.username | default $username }}
  {{- $migPassword := .Values.database.migration.password | default $password }}

  POSTGRES_HOST: {{ $host | b64enc | quote }}
  POSTGRES_PORT: {{ printf "%d" $port | b64enc | quote }}
  POSTGRES_DB: {{ $dbName | b64enc | quote }}
  POSTGRES_SSL_MODE: {{ $sslMode | b64enc | quote }}
  POSTGRES_USER: {{ $username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ $password | b64enc | quote }}

  MIGRATION_DATABASE_URL: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=%s" $migUsername $migPassword $host $port $dbName $sslMode | b64enc | quote }}
{{- end }}
