{{- if not .Values.kek.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "defined.kekSecretName" . }}
  labels:
    {{- include "defined.labels" . | nindent 4 }}
type: Opaque
data:
  KEK: {{ .Values.kek.key | b64enc | quote }}
{{- end }}