{{- if not .Values.redis.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "defined.redisSecretName" . }}
  labels:
    {{- include "defined.labels" . | nindent 4 }}
type: Opaque
data:
  REDIS_ADDR: {{ .Values.redis.addr | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | default "" | b64enc | quote }}
  REDIS_DB: {{ .Values.redis.db | default 0 | printf "%d" | b64enc | quote }}
  REDIS_MODE: {{ .Values.redis.mode | default "standalone" | b64enc | quote }}
  REDIS_SENTINEL_MASTER: {{ .Values.redis.sentinelMasterName | default "" | b64enc | quote }}
  REDIS_SENTINEL_PASSWORD: {{ .Values.redis.sentinelPassword | default "" | b64enc | quote }}
{{- end }}
