{{- $configRefs := list -}}
{{- $configRefs = append $configRefs (dict
  "type" "configMap"
  "name" (include "pms-lib.configs.http.configMapName" (dict "component" "client" "root" $))
  "template" "pms-lib.config.http"
  "params" (dict "component" "client" "prefix" "HTTP_" "config" .Values "root" $)
) -}}
{{- if .Values.database.enabled -}}
{{- $configRefs = append $configRefs (dict
  "type" "configMap"
  "name" (include "pms-lib.configs.db.configMapName" (dict "component" "client" "root" $))
  "template" "pms-lib.config.db"
  "params" (dict "component" "client" "prefix" "DB_" "config" .Values "root" $)
) -}}
{{- $configRefs = append $configRefs (dict
  "type" "secret"
  "name" (include "pms-lib.configs.db.secretName" (dict "component" "client" "config" .Values "root" $))
  "template" "pms-lib.config.db"
  "params" (dict "component" "client" "prefix" "DB_" "config" .Values "root" $)
) -}}
{{- end -}}
{{- include "pms-lib.deployment" (dict
  "component" "client"
  "config" .Values
  "configRefs" $configRefs
  "root" $
) }}
