// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ClientApp is the predicate function for clientapp builders.
type ClientApp func(*sql.Selector)

// Service is the predicate function for service builders.
type Service func(*sql.Selector)
